### ISSUE TITLE
The validator instance is not working

### ISSUE THREAD

**Issue by jakubklimek** [SEMICeu/dcat-ap_validator#10]
The instance at http://data.opendatasupport.eu:3030/dcat-ap_validator.html is not working, any idea why?

**Comment by EmidioStani** [comment]
Hello Jakub,

as far as I know the public instance of the validator has been currently shutdown while the project is in the process of being moved between 2 contracts. I am sorry for this service interruption.

For the moment I can only suggest to download the zip file on Joinup:

https://joinup.ec.europa.eu/software/dcat-ap_validator/asset_release/dcat-ap-validation-service-110

**Comment by marcomb** [comment]
It could be crucial to have a unique validator instance, shared across Europe, in order to improve quality of DCAT-AP adoption and overall standardization. Keep us updated if you have any news about it. Thanks

**Comment by EmidioStani** [comment]
@jakubklimek @marcomb As I don't have news, I put in place anyway an istance of the validator which can found here: http://52.50.205.146:3031/dcat-ap_validator.html

**Comment by marcomb** [comment]
Dear Emilio, your validator istance is down, it was very useful to have it up. Could you setup it again for a while? Thanks!

**Comment by EmidioStani** [comment]
Sorry for replying just now, busy on other projects, the validator is up and running again, thanks a lot for informing me!

**Comment by dafeder** [comment]
@EmidioStani the validator is down again and has been for a while I believe.

**Comment by EmidioStani** [comment]
Hello @dafeder, I have just put it on, we increased the memory and disk on the amazon machine so some service were down

**Comment by jb3-2** [comment]
Hi @EmidioStani, the validator at http://52.50.205.146:3031/dcat-ap_validator.html does not seem to be up and running. Can you maybe restart it? Thanks a lot! J.

**Comment by EmidioStani** [comment]
Hi @jb3-2 sorry to reply just now, the service has been restarted

**Comment by jb3-2** [comment]
Hi @EmidioStani, thnak you, but somehow this link still does not work... http://52.50.205.146:3031/dcat-ap_validator.html

**Comment by EmidioStani** [comment]
Hello @jb3-2 the validator is accessible, can you try again ? can you access to applications outside port 80?

**Comment by jb3-2** [comment]
Sorry, you're right, it was a corporate firewall issue... Server is up and running. Thanks! J

**Comment by EmidioStani** [comment]
No problem, if you think that it can be a problem, I can put it on port 80

**Comment by jb3-2** [comment]
Port 80 would be perfect, if it's no big thing to do for you... Thanks! J.

**Comment by EmidioStani** [comment]
Validator is now available at:

http://dcat-ap.semic.eu/dcat-ap_validator.html

**Comment by jakubklimek** [comment]
@EmidioStani http://dcat-ap.semic.eu/dcat-ap_validator.html results in
```
Error 08001

HT016: Cannot connect to 52.50.205.146:3031 in http_get
```

**Comment by addragan** [comment]
Proposed resolution: It is proposed to deprecate the DCAT-AP Validator as it is being moved on the ISA Test Bed solution and closing the issue.
