### ISSUE TITLE
Installation instructions seem to be outdated

### ISSUE THREAD

**Issue by jakubklimek** [SEMICeu/dcat-ap_validator#20]
After deploying validators pages folder to fuseki, the dcat-ap_validator.html page searches for ```/css/concat/dcat.css``` and ```/js/concat/dcat.js```, however there is no ```concat``` folder, only various other subfolders of ```/css```and ```/js```, so it does not work.

**Comment by addragan** [comment]
Proposed resolution: It is proposed to deprecate the DCAT-AP Validator as it is being moved on the ISA Test Bed solution and closing the issue.
