### ISSUE TITLE
Checks for vcard:Kind are incorrect

### ISSUE THREAD

**Issue by jakubklimek** [SEMICeu/dcat-ap_validator#8]
See the <a href="https://www.w3.org/TR/vcard-rdf/#d4e1819">VCard</a> specification. vcard:Kind is a superclass, it actually does not specify the kind of the VCard. Therefore, its usage should not be valid. Instead, the usage of the sub-classes should be encouraged (Group, Individual, Location, Organization), which is now treated as invalid.

**Comment by EmidioStani** [comment]
Hello Jakub,

I believe you are right here. It is true indeed that on rule:

http://data.opendatasupport.eu:3030/sparql-doc/rule-43.html

I validate against a vcard:Kind which is supposed to be a superclass.

I propose to keep the issue active.

**Comment by addragan** [comment]
Proposed resolution: It is proposed to deprecate the DCAT-AP Validator as it is being moved on the ISA Test Bed solution and closing the issue.
